spring.application.name=spring-practice
server.port=8081

# ?????? ?? ??
spring.datasource.url=jdbc:mysql://localhost:3306/spring_practice_db
spring.datasource.username=spring_practice
spring.datasource.password=1234
spring.datasource.driver-class-name=com.mysql.cj.jdbc.Driver

# JPA ?? ??
spring.jpa.database-platform=org.hibernate.dialect.MySQL8Dialect
# (create, update, validate, none ? ?? ??)
spring.jpa.hibernate.ddl-auto=none
# SQL ?? ?? ?? ??
spring.jpa.show-sql=true
# SQL ?? ?? ??
spring.jpa.properties.hibernate.format_sql=true
# Open-Entity-Manager ?? (?? ??)
spring.jpa.open-in-view=false
# stock-api-keys
stock-api.appkey=
stock-api.appsecret=
